baseurl: "/JazlynC-Portfolio"
title: Jazlyn Collyear
description: Senior Cybersecurity Student @ Indiana Tech
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - work.md
  - about.md
  - Resume_Jazlyn Collyear.pdf
